/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;

import database.Koneksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Farha
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    private Connection conn = new Koneksi().connect();
    private DefaultTableModel tabmode;
    
    public MenuUtama() {
        initComponents();
        mainTable.setVisible(false);
        title.setVisible(false);
        btn_menu_tambah_data.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        panelRound1 = new component.PanelRound();
        btn_menu_karyawan = new com.k33ptoo.components.KButton();
        btn_menu_member = new com.k33ptoo.components.KButton();
        btn_menu_layanan = new com.k33ptoo.components.KButton();
        btn_menu_transaksi = new com.k33ptoo.components.KButton();
        title = new javax.swing.JLabel();
        btn_menu_tambah_data = new com.k33ptoo.components.KButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelRound1.setRoundBottomRight(60);
        panelRound1.setRoundTopRight(60);

        btn_menu_karyawan.setText("Data Karyawan");
        btn_menu_karyawan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_menu_karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menu_karyawanActionPerformed(evt);
            }
        });

        btn_menu_member.setText("Data Member");
        btn_menu_member.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_menu_member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menu_memberActionPerformed(evt);
            }
        });

        btn_menu_layanan.setText("Data Layanan");
        btn_menu_layanan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_menu_layanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menu_layananActionPerformed(evt);
            }
        });

        btn_menu_transaksi.setText("Transaksi");
        btn_menu_transaksi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_menu_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menu_transaksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_menu_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_menu_member, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_menu_layanan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_menu_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btn_menu_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_menu_member, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_menu_layanan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_menu_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(328, Short.MAX_VALUE))
        );

        title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Data Member");
        title.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        btn_menu_tambah_data.setText("Tambahkan Data");
        btn_menu_tambah_data.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_menu_tambah_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menu_tambah_dataActionPerformed(evt);
            }
        });

        mainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(mainTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 867, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btn_menu_tambah_data, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_menu_tambah_data, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void btn_menu_karyawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menu_karyawanActionPerformed
        // TODO add your handling code here:
        mainTable.setVisible(true);
        title.setVisible(true);
        btn_menu_tambah_data.setVisible(true);
        btn_menu_karyawan.setBackground(btn_menu_member.getkPressedColor());
        title.setText("Karyawan");
        
        Object[] Baris = {"No ID", "Nama Karyawan", "Username"};
        tabmode = new DefaultTableModel(null, Baris);
        mainTable.setModel(tabmode);
        String sql = "select * from karyawan";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);            
            while(hasil.next()){
                
                String a = hasil.getString("id");
                String b = hasil.getString("nama");
                String c = hasil.getString("username");
                
                String[] data = {a,b,c};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR DATA TABLE :  "+e);
        }
    }//GEN-LAST:event_btn_menu_karyawanActionPerformed

    private void btn_menu_layananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menu_layananActionPerformed
        // TODO add your handling code here:
        mainTable.setVisible(true);
        title.setVisible(true);
        btn_menu_tambah_data.setVisible(true);
        btn_menu_layanan.setBackground(btn_menu_member.getkPressedColor());
        title.setText("Layanan");
        
        Object[] Baris = {"No ID", "Nama Layanan", "Harga", "Point Price"};
        tabmode = new DefaultTableModel(null, Baris);
        mainTable.setModel(tabmode);
        String sql = "select * from layanan";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);            
            while(hasil.next()){
                
                String a = hasil.getString("id");
                String b = hasil.getString("nama");
                String c = hasil.getString("harga");
                String d = hasil.getString("point_price");
                
                String[] data = {a,b,c, d};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR DATA TABLE :  "+e);
        }
    }//GEN-LAST:event_btn_menu_layananActionPerformed

    private void btn_menu_memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menu_memberActionPerformed
        // TODO add your handling code here:
        mainTable.setVisible(true);
        title.setVisible(true);
        btn_menu_tambah_data.setVisible(true);
        btn_menu_member.setBackground(btn_menu_member.getkPressedColor());
        title.setText("Member");
        
        btn_menu_tambah_data.addActionListener((e) -> {
            new FormMember().setVisible(true);
        });
        
        Object[] Baris = {"No ID", "Nama Member", "Alamat", "Tanggal Lahir"};
        tabmode = new DefaultTableModel(null, Baris);
        mainTable.setModel(tabmode);
        String sql = "select * from member";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);            
            while(hasil.next()){
                
                String a = hasil.getString("id");
                String b = hasil.getString("nama");
                String c = hasil.getString("alamat");
                String d = hasil.getString("tgl_lahir");
                
                String[] data = {a,b,c, d};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR DATA TABLE :  "+e);
        }
    }//GEN-LAST:event_btn_menu_memberActionPerformed

    private void btn_menu_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menu_transaksiActionPerformed
        // TODO add your handling code here:
        mainTable.setVisible(true);
        title.setVisible(true);
        btn_menu_tambah_data.setVisible(true);
        btn_menu_transaksi.setBackground(btn_menu_member.getkPressedColor());
        title.setText("Transaksi");
        
        Object[] Baris = {"No ID", "Nama Member", "Nama Karyawan", "Total Harga", "Tanggal"};
        tabmode = new DefaultTableModel(null, Baris);
        mainTable.setModel(tabmode);
        String sql = "select * from transaksi t, member m, karyawan k where t.id_member = m.id and t.id_karyawan = k.id";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);            
            while(hasil.next()){
                
                String a = hasil.getString("t.id");
                String b = hasil.getString("m.nama");
                String c = hasil.getString("k.nama");
                String d = hasil.getString("t.total_harga");
                String e = hasil.getString("t.tanggal");
                
                String[] data = {a,b,c,d,e};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR DATA TABLE :  "+e);
        }
    }//GEN-LAST:event_btn_menu_transaksiActionPerformed

    private void btn_menu_tambah_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menu_tambah_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_menu_tambah_dataActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btn_menu_karyawan;
    private com.k33ptoo.components.KButton btn_menu_layanan;
    private com.k33ptoo.components.KButton btn_menu_member;
    private com.k33ptoo.components.KButton btn_menu_tambah_data;
    private com.k33ptoo.components.KButton btn_menu_transaksi;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable mainTable;
    private component.PanelRound panelRound1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
