/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Farha
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
    }
    
    public void start(){
//        Login login = new Login();
//        login.setVisible(true);
        
        setResizable(false);
        setVisible(true);
        try {
            for (int i = 0; i <= 5; i++) {
                                
                Thread.sleep(200);
                if (i % 2 == 0) {
                    txtLoading.setText("Please wait..");                
                }else {
                    txtLoading.setText("Please wait");      
                }            
            }
        } catch (InterruptedException ex) {
            Logger.getLogger(SplashScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            for (int i = 0; i <= 100; i++) {
                progressBarCostume1.setValue(i);
                progressBarCostume1.setString(i+"%");
                txtPersen.setText(i+"%");

                if (i >= 70 ) {
                    if (i % 2 == 0) {
                        txtLoading.setText("Connect to Database..");
                    }else {
                        txtLoading.setText("Connect to Database");
                    }
                }else if (i >= 20) {
                    if (i % 2 == 0) {
                        txtLoading.setText("Load Module..");
                    }else {
                        txtLoading.setText("Load Module");
                    }
                }else {
                    if (i % 2 == 0) {
                    txtLoading.setText("Please wait..");                
                    } else {
                    txtLoading.setText("Please wait");      
                    }  
                }
                Thread.sleep(100);
                
                if (i == 100){
                    txtLoading.setText("Connecting Ok");
                    Login login = new Login();
                    dispose();
                    Thread.sleep(400);
                    login.setVisible(true);
                }
            }
        } catch (InterruptedException e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        progressBarCostume1 = new component.ProgressBarCostume();
        txtLoading = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtPersen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(255, 51, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 255, 255));

        progressBarCostume1.setBackground(new java.awt.Color(0,0,0,0)
        );
        progressBarCostume1.setColorString(new java.awt.Color(255, 255, 255));
        progressBarCostume1.setOpaque(false);
        progressBarCostume1.setStringPainted(false);

        txtLoading.setBackground(new java.awt.Color(255, 255, 255));
        txtLoading.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtLoading.setForeground(new java.awt.Color(255, 255, 255));
        txtLoading.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtLoading.setText("Please Wait...");
        txtLoading.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/logo-salon-large.png"))); // NOI18N

        txtPersen.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtPersen.setForeground(new java.awt.Color(255, 255, 255));
        txtPersen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtPersen.setText("0%");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(progressBarCostume1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addGap(0, 62, Short.MAX_VALUE)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(txtPersen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLoading, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLoading)
                    .addComponent(txtPersen))
                .addGap(18, 18, 18)
                .addComponent(progressBarCostume1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private component.ProgressBarCostume progressBarCostume1;
    private javax.swing.JLabel txtLoading;
    private javax.swing.JLabel txtPersen;
    // End of variables declaration//GEN-END:variables
}
